// const express = require("express")
// const _ = express.Router()
// const categoryController = require("../../controller/category/categoryController")
// const allCategory = require('../../controller/category/AllCategory')
// const allSubCategory = require('../../controller/sub category/allSubCategory')
// const allSubCategories = require('../../controller/sub category/allSubCategory')
// const deleteCategoryController = require('../../controller/category/deleteCategoryController')
// const editCategoryController = require('../../controller/category/editCategoryController')
// const createSubCategoryController = require('../../controller/sub category/subCategoryController')
// const deleteSubCategoryController = require('../../controller/category/deleteSubCategoryController')
// const editSubCategoryController = require('../../controller/sub category/editSubCategoryController')
// const categoryAproveController = require('../../controller/category/categoryAproveController')
// const categoryHoldController = require('../../controller/category/categoryHoldController')
// const subcategoryAproveController = require('../../controller/sub category/subcategoryAproveController')
// const subCategoryHoldController = require('../../controller/sub category/subCategoryHoldController')
   
// _.post("/createcategory", categoryController)
// _.post("/create-subcategory", createSubCategoryController)
// _.get("/allcategory", allCategory)
// _.get("/allsubcategory", allSubCategories)
// _.post("/deleteCategory", deleteCategoryController)
// _.post("/deletesubcategory", deleteSubCategoryController)
// _.post("/editcategory", editCategoryController)
// _.post("/editsubcategory", editSubCategoryController)
// _.post("/categoryaprove", categoryAproveController)
// _.post("/subcategoryaprove", subcategoryAproveController)
// _.post("/categoryhole", categoryHoldController)
// _.post("/subcategoryhold", subCategoryHoldController)
  
// module.exports = _